### ISSUE TITLE
Zmiana widoczności Repo RC---LO-501-lrp-cicaplast-LT 

### ISSUE THREAD

**Issue by joannawalach1** [eStoreLabs/RC---LO-501-lrp-cicaplast-LT#1]
Prośba z zmianę widoczności repo, 
przez pomyłkę ustawione na private, 
https://github.com/eStoreLabs/RC---LO-501-lrp-cicaplast-LT
Dziękuję.

**Comment by Domi-eStore** [comment]
zrobione
